name: Check docker base image

on:
  schedule:
    - cron:  '*/5 * * * *'

env:
  REGISTRY: hub.docker.com
  DOCKER_HUB_NAMESPACE: rhessing
  BASE_IMAGE: node:bullseye

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: ${{ env. BASE_IMAGE }}
          image: ${{ env.DOCKER_HUB_NAMESPACE }}/${{ github.repository }}:latest

      - name: Login to Docker Hub
        continue-on-error: true
        if: steps.check.outputs.needs-updating == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        continue-on-error: true
        if: steps.check.outputs.needs-updating == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        continue-on-error: true
        if: steps.check.outputs.needs-updating == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ github.repository }}:latest
